### ISSUE TITLE
Search Bar Recherche 

### ISSUE THREAD

**Issue by GhassenAskri** [GhassenAskri/BeegoForTest#5]
![image](https://user-images.githubusercontent.com/19927564/41288642-5344ad8e-6e47-11e8-8abc-886aac2323cf.png)

Largeur de lespace recherche  : 375px;
![burger_menu](https://user-images.githubusercontent.com/19927564/41288936-5a396958-6e48-11e8-85ca-d39dc9f0e39a.png)

Si tu as besoin de quelques chose exporte les éléments depuis mon pc

**Comment by nour023** [comment]
![nav-acceuil](https://user-images.githubusercontent.com/39799816/41344204-d0675654-6f00-11e8-9ce2-0255d1e34ef0.jpg)
![vav-search](https://user-images.githubusercontent.com/39799816/41344213-d3b8426e-6f00-11e8-9a37-462261937f87.jpg)
